# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f30fa70002a4d2325df003bdffd57393520eaf7fa77e462730bfcbb4921c22deb7a33f61cf5dbe210a463875ecac0571d258a41f91e571fe769b1e77286be05d

test:
  secret_key_base: 9caf67f1412579560efd0927e961335e925443a50484dbbbebc9a3c33f9236b1014b016ec5ff4d339110150d6f451a1ed42e0890567ddace40254e41fcb79c09

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
